// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cidxcujlfkrzvvmljxqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZHhjdWpsZmtyenZ2bWxqeHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NTIyNTAsImV4cCI6MjA4NTEyODI1MH0._6UFO0UHSssA6iDROrPRMYmYfCdDtEz_F9hx2gOU8DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});